### ISSUE TITLE
Bug report - TI-84 plus CE-T Python Edition

### ISSUE THREAD

**Issue by PrivateDragon** [YvanTT/arTIfiCE#1] opened 2020-09-11 04:54 UTC
### Describe the bug clearly: what happens: crash? reset? freeze? ...
I helped a friend with arTIfiCE, at first it woked, but then it suddenly crashed and the RAM got cleared.

### How to reproduce the bug
1. Again sending the apps and overwriting, and playing them using arTIfiCE

### Calculator version
This is the most important part:
Which calculator: **TI-84 Plus CE-T Python Edition**

- **Which Boot and OS versions is the calculator running:**
**Boot: 5.5.0.0006** ; **OS: 5.5.5.0011**

- **Which hardware revision is your calculator:**
?

- **Approximately when did you buy the calculator:**
**the end of August**

### Additional info / Screenshots / Video
![VID_20200911_104041_5](https://user-images.githubusercontent.com/70799817/92934308-9e112300-f447-11ea-970d-323d1d101f68.gif)

**Comment by mateoconlechuga** [comment] 2020-09-11 13:09
Can't help you if you aren't willing to fill in the above information.

**Comment by YvanTT** [comment] 2020-09-11 13:33
Did the crash happen after you tried to launch a program/game from within the program list (arTIfiCE shell)?
Or did it happen right away when opening arTIfiCE from Cabri?

I haven't been able to reproduce a crash on OS 5.5.5, and I'm reading successful tests here and there too, so maybe you're trying to launch something that's not compatible yet with OS 5.5/5.6 (check with the program authors if there are any updates).

One more tip: Since OS 5.3.0, you can basically send all programs to the Archive instead of RAM, they will work just fine, and if a crash happens you will not lose them :)

**Comment by PrivateDragon** [comment] 2020-09-11 14:07
I've updated the post and added a video.
It happens after selecting a program with ArTIfiCE.
Updatet os to 5.6 but didn't matter, the problem still exists.
But the strange thing is that on my calculator,  which is the same type and os the problem doesn't exist...
Maybe because I couldn't send Cesium to my friend?

**Comment by YvanTT** [comment] 2020-09-11 15:36
Ah, actually it would be a good idea to remove the USB after transferring the file (and before launching cabri and artifice).
Can you try that?

**Comment by PrivateDragon** [comment] 2020-09-11 15:42
Hmmm, maybe it works.
But then we will have to try again on Monday.
BTW, could it also have been the problem that his calculator was not fully charged?
I don't think so, but maybe?

**Comment by TheLastMillennial** [comment] 2020-09-14 20:39
I've had two commenters on my jail breaking video having issues with artifice freezing. They both have a CE-T Python Edition running OS 5.6.0.0020. However, one person has BOOT 5.5.0.0006 and revision L-0620P while the other has BOOT 5.3.1.0050 and revision L-0519L.

**Comment by adriweb** [comment] 2020-09-14 23:47
(Quick note: even though I have no idea about the freeze (I'll let @YvanTT or others try to find out what's going on), I just wanted to clarify that A CE-T Python Edition is only rev P or later btw, so that second person probably had a non-python (and even before rev M) 84+CET)

**Comment by PrivateDragon** [comment] 2020-09-15 04:26
We tried it again yesterday,  but that didn't solve the problems.
At some point with another game the calculator actually really froze,  so we had to remove the battery...

We are going to install Cesium, and try if the problem still exists after launching a game from Cesium

**Comment by adriweb** [comment] 2020-09-15 04:58
It would be interesting to know if this happens only on the 84 Plus CE-T Python Edition, maybe there is something different no one knows about...

**Comment by PrivateDragon** [comment] 2020-09-15 05:01
I don't think so.
I have also the Python Edition,  but I don't have the problem.
But because I have also Cesium, and my friend not, we think that might then be the problem, so today we're going to install Cesium on his calc too and see if that helps....

**Comment by TheLastMillennial** [comment] 2020-09-15 17:13
I had another person with an issue, they have all the stock settings and default apps.
Here's my updated list of calculators that are having issues:
- CE-T Python Edition with OS 5.5.5.0011, BOOT 5.5.0.0006, and revision L-0520P
- CE-T Python Edition with OS 5.6.0.0020, BOOT 5.5.0.0006, and revision L-0620P
- Regular CE-T with OS 5.6.0.0020, BOOT 5.3.1.0050, and revision L-0519L.

**Comment by YvanTT** [comment] 2020-09-15 17:14
Hello, 

I cannot reproduce this issue so far, and I also don't really know if it's due to a difference in these new hardware versions :(

In the meantime, I recommend using [Cesium](https://github.com/mateoconlechuga/cesium/releases/latest) as the default way to launch your programs. I recently learned about [AsmHook](https://github.com/jacobly0/asmhook/releases/latest), so this is also a good way to launch programs directly from the home screen. If you want to use Cesium at the same time, make sure to have the latest version.

@TheLastMillennial Does the problem happen if they launch programs using Cesium too? Or only the arTIfiCE shell?

Thank you for your feedback, I will try to improve the stability on the CE-T when the problem is identified...

**Comment by TheLastMillennial** [comment] 2020-09-15 17:31
@YvanTT I believe it's only when they try to launch programs with arTIfiCE because they said they couldn't install things since it would freeze or crash.

**Comment by PrivateDragon** [comment] 2020-09-16 08:36
We have now installed Cesium and launched the,appps from there, that solves the problem.

So according to this, I would think that launching apps from the arTIfiCE shell just doesn't work good.
So that you really have to use Cesium to launch apps without getting crashes.

**Comment by YvanTT** [comment] 2020-09-16 17:34
Hello!

A new version will be ready to test soon (I'll post it here), it should improve stability with Cabri and fix some APD-related things. Hopefully it will fix the problems some people have been experiencing.
Once that is validated here, I will make a new v1.1 release and mention it on the web page.

Thanks

**Comment by YvanTT** [comment] 2020-09-16 23:29
Here it is, please test this version (open/extract the zip and transfer the 8xv file inside on your calc, and open with the Cabri app) and let me know if it works better!
[arTIfiCE_beta.zip](https://github.com/YvanTT/arTIfiCE/files/5235385/arTIfiCE_beta.zip)

Thanks, I'll go to bed now it's already way too late :D

**Comment by PrivateDragon** [comment] 2020-09-17 19:24
I'll test it this weekend if possible. 
(Because I've Linux and only my father has the root password I can't download Tilp, so every time I have to go to friends, so I hope they have time😅.. )

**Comment by PrivateDragon** [comment] 2020-09-21 06:39
The problem seems to be solved with this new version.
I'll try to test it more extensively later today.

**Comment by PrivateDragon** [comment] 2020-09-22 05:24
I've succesfully launched several programs. 
No problem found.

**Comment by YvanTT** [comment] 2020-09-22 13:59
Thanks! I will create release v1.1 then.

**Closed by YvanTT** 2020-09-22 13:59 UTC
